updated readme
eastgenomics/optimised_filtering pull request #7
Opened 2023-11-20 09:46 UTC by chrispyatt

removed references to zygosity filtering, and PRIORITISED/NOT_PRIORITISED tags

2023-11-20 11:32 UTC, chrispyatt commented
not sure how I closed this but have now reopened

2023-11-20 11:40 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/7)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[`README.md` line 56 at r2](https://reviewable.io/reviews/eastgenomics/optimised_filtering/7#-NjgWysVBUBic4xeyGpG:-NjgWysW0D7zhTpjCqbo:b-kaxemc) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/528f56659606b2efce9a0876ceba4078f57554b6/README.md#L56)):*
> ```Markdown
> ```JSON
> {
> 	"bcftools_filter_string": "bcftools filter --soft-filter \"EXCLUDE\" -m + -e '(CSQ_Consequence~\"synonymous_variant\" | CSQ_Consequence~\"intron_variant\" | CSQ_Consequence~\"upstream_gene_variant\" | CSQ_Consequence~\"downstream_gene_variant\" | CSQ_Consequence~\"intergenic_variant\" | CSQ_Consequence~\"5_prime_UTR_variant\" | CSQ_Consequence~\"3_prime_UTR_variant\" | CSQ_gnomADe_AF>0.01 | CSQ_gnomADg_AF>0.01 | CSQ_TWE_AF>0.05) & CSQ_ClinVar_CLNSIGCONF!~ \"pathogenic\\/i\" & (CSQ_SpliceAI_pred_DS_AG<0.2 | CSQ_SpliceAI_pred_DS_AG==\".\") & (CSQ_SpliceAI_pred_DS_AL<0.2 | CSQ_SpliceAI_pred_DS_AL==\".\") & (CSQ_SpliceAI_pred_DS_DG<0.2 | CSQ_SpliceAI_pred_DS_DG==\".\") & (CSQ_SpliceAI_pred_DS_DL<0.2 | CSQ_SpliceAI_pred_DS_DL==\".\") | (MOI=\"BIALLELIC\" & (CSQ_gnomadg_AF>0.005 | CSQ_gnomade_AF>0.005))'"
> ```

is this stupid? Would it be better to keep the filtering rules above and refer to them (how?) in the bcftools string


<!-- Sent from Reviewable.io -->

2023-11-20 13:26 UTC, mattgarner requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/7)* status: all files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

___
*[`README.md` line 56 at r2](https://reviewable.io/reviews/eastgenomics/optimised_filtering/7#-NjgWysVBUBic4xeyGpG:-Njgu4Nq-H2bAm4o53_u:b-exukb) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/528f56659606b2efce9a0876ceba4078f57554b6/README.md#L56)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

is this stupid? Would it be better to keep the filtering rules above and refer to them (how?) in the bcftools string
</blockquote></details>

Discussed. A separate config is not necessary/desirable so this will become a string input


<!-- Sent from Reviewable.io -->

2023-11-21 13:52 UTC, pep8speaks commented
Hello @chrispyatt! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/add_optimised_filtering.py`](https://github.com/eastgenomics/optimised_filtering/blob/2b4ef47f5b13760a4553852558be6840cfe8bad3/resources/add_optimised_filtering.py):

> [Line 110:49](https://github.com/eastgenomics/optimised_filtering/blob/2b4ef47f5b13760a4553852558be6840cfe8bad3/resources/add_optimised_filtering.py#L110): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\!'

2023-11-21 13:56 UTC, closed without merging