Di 499 readme change
eastgenomics/optimised_filtering pull request #9
Opened 2023-11-21 13:55 UTC by chrispyatt

added bcftools as input

also added csq fields to split as an input (realised that should have been in config example)

fixed some other small bugs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/optimised_filtering/9)

2023-11-21 13:55 UTC, pep8speaks commented
Hello @chrispyatt! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/add_optimised_filtering.py`](https://github.com/eastgenomics/optimised_filtering/blob/a6a779fe0eaee5e5e03252e6ba23b33a3a03aa0e/resources/add_optimised_filtering.py):

> [Line 110:49](https://github.com/eastgenomics/optimised_filtering/blob/a6a779fe0eaee5e5e03252e6ba23b33a3a03aa0e/resources/add_optimised_filtering.py#L110): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\!'

2023-11-22 10:35 UTC, mattgarner requested changes
> Reviewed 2 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/9)* status: all files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

___
*[`dxapp.json` line 53 at r3](https://reviewable.io/reviews/eastgenomics/optimised_filtering/9#-Njq_nkg5KIRkaCbTxVr:-Njq_nkh8PIoUpEEn5xN:b45h) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/dbad7a8b31cf5314d17f56819d131bd61d84332c/dxapp.json#L53)):*
> ```JSON
>         },
>         {
>         "name": "csq_to_slit",
> ```





_Suggestion:_
```JSON
split
```


<!-- Sent from Reviewable.io -->

2023-11-22 10:55 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/9)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[`dxapp.json` line 53 at r3](https://reviewable.io/reviews/eastgenomics/optimised_filtering/9#-Njq_nkg5KIRkaCbTxVr:-Njqeupr14XS6KrWanNI:b-896fix) ([raw file](https://github.com/eastgenomics/optimised_filtering/blob/dbad7a8b31cf5314d17f56819d131bd61d84332c/dxapp.json#L53)):*
> ```JSON
>         },
>         {
>         "name": "csq_to_slit",
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 15:18 UTC, mattgarner approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/optimised_filtering/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrispyatt)



<!-- Sent from Reviewable.io -->

2023-11-22 15:18 UTC, merged